version: "3.9"

services:
    backend:

        container_name: django-practice

        build: .
        
        volumes:
            - .:/app

        ports:
            - "8000:8000"
        
        command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
