version: "3.9"

services:
    backend:
        container_name: django-practice
        build: .        
        volumes:
            - .:/app
        ports:
            - "8000:8000"        
        command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - redis
            - db

    redis:
        image: redis:latest
        restart: always
        container_name: redis1
        ports:
            - "6379:6379"
        command: redis-server --save 60 1 --loglevel warning

    db:
        container_name: pg-db1
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file:
            - .env
        restart: always

    worker-celery:
        build: .
        container_name: worker-celery1
        volumes:
            - .:/app
        command: celery -A core worker --loglevel=info
        depends_on:
            - redis
            - backend

    beat-celery:
        build: .
        container_name: beat-celery1
        volumes:
        - .:/app
        command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
        depends_on:
        - redis
        - backend

    smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            # Change the number before : to the port the web interface should be accessible on
            - '5000:80'
            # Change the number before : to the port the SMTP server should be accessible on
            - '25:25'
            # Change the number before : to the port the IMAP server should be accessible on
            - '143:143'
        volumes:
        # This is where smtp4dev stores the database..
            - smtp4dev-data:/smtp4dev
        environment:
            #Specifies the URLs the web UI will use inside the container.
            - ServerOptions__Urls=http://*:80
            #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
            - ServerOptions__HostName=smtp4dev

volumes:
  smtp4dev-data:
  postgres_data: