# Generated by Django 5.2.6 on 2025-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verficated",
            field=models.BooleanField(default=False, verbose_name="تاییدشده/تاییدنشده"),
        ),
    ]
