# Generated by Django 5.2 on 2025-09-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("todos", "0002_todo_author_todo_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
                verbose_name="نویسنده",
            ),
        ),
    ]
